version: '3'
services:
  nginx_rtmp:
    build: ./nginx_rtmp
    ports:
     - "3110:80"
     - "1935:1935"
    volumes:
     - ./nginx_rtmp/conf/nginx.conf:/usr/local/nginx/conf/nginx.conf
     - ./nginx_rtmp/html/video:/usr/local/nginx/html/video
     - ./nginx_rtmp/videos:/usr/local/nginx/html/videos
